services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: newsdigest
      POSTGRES_USER: newsdigest
      POSTGRES_PASSWORD: newsdigest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: uv run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://newsdigest:newsdigest@postgres:5432/newsdigest
      REDIS_URL: redis://redis:6379/0
      DJANGO_DEBUG: "true"
    depends_on:
      - postgres
      - redis

  worker:
    build: .
    command: uv run celery -A config.celery_app worker -l info
    environment:
      DATABASE_URL: postgres://newsdigest:newsdigest@postgres:5432/newsdigest
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  beat:
    build: .
    command: uv run celery -A config.celery_app beat -l info
    environment:
      DATABASE_URL: postgres://newsdigest:newsdigest@postgres:5432/newsdigest
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:

