name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e newsdigest
          pip install djlint pytest pytest-django factory_boy

      - name: djLint
        run: |
          djlint newsdigest --check

      - name: Pytest (SQLite)
        env:
          PYTHONPATH: newsdigest
          DJANGO_SETTINGS_MODULE: config.settings.test
          DATABASE_URL: sqlite:///./test_db.sqlite3
        run: |
          pytest -q


